[build]
  publish = "."
  command = ""

# Cấu hình headers cho trang redirect
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Cấu hình redirect (tùy chọn)
# [[redirects]]
#   from = "/*"
#   to = "https://www.google.com"
#   status = 301